CREATE TABLE STORE (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    revenue DOUBLE DEFAULT 0.00
);

CREATE TABLE PRODUCT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    price DOUBLE NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    store_id INT,
    FOREIGN KEY (store_id) REFERENCES STORE(id)
);

CREATE TABLE EMPLOYEE (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    salary DOUBLE NOT NULL,
    store_id INT,
    FOREIGN KEY (store_id) REFERENCES STORE(id)
);

CREATE TABLE CUSTOMER (
    id INT PRIMARY KEY AUTO_INCREMENT,
    money DOUBLE NOT NULL DEFAULT 0
);

CREATE TABLE SALES (
    id INT PRIMARY KEY AUTO_INCREMENT,
    customer_id INT,
    product_id INT,
    quantity INT NOT NULL,
    sale_turn INT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES CUSTOMER(id),
    FOREIGN KEY (product_id) REFERENCES PRODUCT(id)
);
